# This is assignment10

## Name : Jaehyun Lim
    
## Student ID : 20145450

$$ \widetilde{f} (x;\theta) =  \theta _{1} f_{1}(x) + \theta _{2} f_{2}(x)+ \theta _{3} f_{3}(x) + \cdots + \theta _{p} f_{p}(x) $$

$$ \begin{bmatrix}r_{1}^{T}x_1 & r_{2}^{T}x_1 + \cdots + r_{p}^{T}x_1 \\ r_{1}^{T}x_2 & r_{2}^{T}x_2 + \cdots + r_{p}^{T}x_2 \\ \vdots & \vdots  + \cdots +  \vdots  \\ r_{1}^{T}x_n & r_{2}^{T}x_n + \cdots + r_{p}^{T}x_n \end{bmatrix}
\begin{bmatrix} \theta _{1} \\ \theta _{2} \\ \vdots \\ \theta _{p} \end{bmatrix} = \begin{bmatrix}y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix} $$

## import packages 

In [144]:
import numpy as np
import os
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
from sklearn import metrics

In [145]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')
mnist

{'DESCR': 'mldata.org dataset: mnist-original',
 'COL_NAMES': ['label', 'data'],
 'target': array([0., 0., 0., ..., 9., 9., 9.]),
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)}

In [146]:
X, y = mnist["data"], mnist["target"]
X.shape

(70000, 784)

In [147]:
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [148]:
shuffle_index = np.random.permutation(60000)
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]
mean = 0
std = 1
r = np.random.normal(mean, std, (1,784))
X_train = X_train*r

## Multi classify

In [149]:
from sklearn.linear_model import SGDClassifier
some_digit = X[36000]

sgd_clf = SGDClassifier(max_iter=5, random_state=42)
sgd_clf.fit(X_train, y_train)
sgd_clf.predict([some_digit])

array([0.])

In [150]:
some_digit_scores = sgd_clf.decision_function([some_digit])
some_digit_scores

array([[ 296214.73144022, -144585.01355878, -596828.4141026 ,
          11144.28593063,   -7492.56086482,  276374.91787472,
        -262163.9252349 , -254609.88334609,   52269.25291587,
        -510866.04603688]])

In [151]:
np.argmax(some_digit_scores)

0

In [152]:
sgd_clf.classes_

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [153]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict

forest_clf = RandomForestClassifier(random_state=42)
forest_clf.fit(X_train, y_train)
forest_clf.predict([some_digit])

array([5.])

## Accuracy

In [154]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
cross_val_score(sgd_clf, X_train_scaled, y_train, cv=3, scoring="accuracy")

array([0.91096781, 0.90909545, 0.90883633])

## confusion matrix

In [155]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf, X_train, y_train, cv=3)

In [156]:
from sklearn.metrics import confusion_matrix

y_train_pred = cross_val_predict(sgd_clf, X_train_scaled, y_train, cv=3)
conf_mx = confusion_matrix(y_train, y_train_pred)
conf_mx

array([[5737,    3,   19,    8,   10,   45,   48,    9,   41,    3],
       [   2, 6475,   49,   33,    6,   42,    8,   11,  106,   10],
       [  53,   44, 5314,  104,   80,   24,   86,   66,  174,   13],
       [  47,   39,  146, 5346,    3,  224,   35,   57,  143,   91],
       [  16,   27,   38,   11, 5367,    8,   56,   33,   85,  201],
       [  83,   45,   39,  192,   70, 4580,  103,   27,  194,   88],
       [  34,   25,   49,    2,   40,   86, 5626,    6,   50,    0],
       [  24,   21,   71,   29,   55,    9,    3, 5831,   14,  208],
       [  46,  145,   67,  158,   12,  136,   56,   30, 5066,  135],
       [  39,   33,   29,   89,  175,   38,    2,  228,   80, 5236]])

## Precision and Recall

$$ precision = \frac{TP}{TP + FP}$$

$$ recall = \frac{TP}{TP + FN}$$

In [157]:
precision = TP / float(TP + FP)
print("precision : ",precision)

recall = TP / float(FN + TP)
print("recall : ",recall)

precision :  1.0
recall :  0.9993668882557771


## F1 Score

$$ F_{1}Score = \frac{2*precision*recall}{precision + recall}$$

In [158]:
f1_score = (2*precision*recall) / (precision + recall)
print(f1_score)

0.9996833438885371


## The link to the github 

https://github.com/JaeHyunLim/assignment.git